import { Dimensions, Platform, StyleSheet } from "react-native";

const FOOTER_HEIGHT = Math.max(
  56,
  Math.round(Dimensions.get("window").height * 0.08),
);
const TODAY_STICKY_HEADER_HEIGHT = 40;
const TIME_PICKER_ITEM_HEIGHT = 44;
const TIME_PICKER_VISIBLE_ROWS = 5;
const TIME_PICKER_SIDE_PADDING =
  ((TIME_PICKER_VISIBLE_ROWS - 1) / 2) * TIME_PICKER_ITEM_HEIGHT;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  body: {
    flex: 1,
    position: "relative",
  },
  content: {
    padding: 16,
  },
  todayStickyHeader: {
    position: "absolute",
    left: 0,
    right: 0,
    height: TODAY_STICKY_HEADER_HEIGHT,
    paddingHorizontal: 16,
    justifyContent: "center",
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderColor: "#f3f4f6",
    zIndex: 30,
    elevation: 30,
  },
  todayStickyHeaderRow: {
    marginTop: -4,
    marginBottom: 0,
  },
  statusBarFill: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    zIndex: 40,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  headerLeft: {
    width: 120,
    flexDirection: "row",
    alignItems: "center",
  },
  headerRight: {
    width: 120,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 18,
    fontWeight: "600",
  },
  menuButton: {
    paddingVertical: 6,
    paddingHorizontal: 6,
  },
  backButton: {
    marginLeft: 6,
  },
  calendarButton: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginRight: 4,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
  },
  selectionBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    padding: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 6,
  },
  selectionText: {
    fontSize: 12,
    color: "#111827",
  },
  bulkDeleteButton: {
    borderWidth: 1,
    borderColor: "#dc2626",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  bulkDeleteButtonDisabled: {
    borderColor: "#fca5a5",
    opacity: 0.5,
  },
  bulkDeleteButtonText: {
    fontSize: 12,
    color: "#dc2626",
  },
  routineSuggestionCard: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    backgroundColor: "#f9fafb",
  },
  routineSuggestionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  routineSuggestionTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#111827",
  },
  routineSuggestionMeta: {
    fontSize: 11,
    color: "#6b7280",
  },
  routineSuggestionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    borderTopWidth: 1,
    borderColor: "#f3f4f6",
  },
  routineSuggestionInfo: {
    flex: 1,
    marginRight: 10,
  },
  routineSuggestionName: {
    fontSize: 13,
    fontWeight: "500",
    color: "#111827",
  },
  routineSuggestionReason: {
    fontSize: 11,
    color: "#6b7280",
    marginTop: 2,
  },
  routineSuggestionActions: {
    alignItems: "flex-end",
  },
  routineSuggestionAdd: {
    borderWidth: 1,
    borderColor: "#111827",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginBottom: 4,
  },
  routineSuggestionAddText: {
    fontSize: 11,
    color: "#111827",
  },
  routineSuggestionDismiss: {
    paddingVertical: 2,
  },
  routineSuggestionDismissText: {
    fontSize: 10,
    color: "#6b7280",
  },
  tagLibraryBox: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 6,
    padding: 10,
    marginBottom: 12,
  },
  tagRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  tagName: {
    flex: 1,
    fontSize: 12,
    color: "#111827",
  },
  tagActionButton: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginLeft: 6,
  },
  tagActionText: {
    fontSize: 12,
    color: "#111827",
  },
  tagDeleteButton: {
    borderColor: "#dc2626",
  },
  tagDeleteText: {
    fontSize: 12,
    color: "#dc2626",
  },
  tagAddRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
  },
  tagAddInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 6,
    padding: 6,
  },
  tagEditInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 6,
    padding: 6,
  },
  mutedText: {
    fontSize: 12,
    color: "#6b7280",
  },
  helperText: {
    fontSize: 12,
    color: "#6b7280",
  },
  linkText: {
    fontSize: 14,
    color: "#1e3a8a",
  },
  exitSelectionButton: {
    alignItems: "center",
    justifyContent: "center",
  },
  exitSelectionButtonText: {
    fontSize: 12,
    color: "#dc2626",
    fontWeight: "600",
  },
  errorText: {
    fontSize: 12,
    color: "#dc2626",
    marginBottom: 8,
  },
  timeBoxList: {
    marginBottom: 12,
  },
  timeBoxSection: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
  },
  timeBoxHeader: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 44,
  },
  timeBoxChevron: {
    width: 20,
    textAlign: "center",
    fontSize: 12,
    color: "#6b7280",
  },
  timeBoxHeaderBody: {
    flex: 1,
  },
  timeBoxTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
  },
  timeBoxTime: {
    fontSize: 12,
    color: "#6b7280",
    marginTop: 2,
  },
  timeBoxTasks: {
    marginTop: 8,
    borderTopWidth: 1,
    borderColor: "#f3f4f6",
    paddingTop: 6,
  },
  timeBoxTaskRow: {
    minHeight: 44,
    justifyContent: "center",
    paddingVertical: 6,
  },
  timeBoxTaskText: {
    fontSize: 13,
    color: "#111827",
  },
  timeBoxEmpty: {
    fontSize: 12,
    color: "#6b7280",
    paddingVertical: 6,
  },
  scheduleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  scheduleLabel: {
    width: 60,
    fontSize: 12,
    color: "#111827",
  },
  scheduleInputs: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  scheduleInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 8,
    fontSize: 12,
  },
  scheduleSeparator: {
    marginHorizontal: 6,
    fontSize: 12,
    color: "#6b7280",
  },
  resetButton: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  resetButtonText: {
    fontSize: 12,
    color: "#111827",
  },
  notesTabRow: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    borderRadius: 8,
    padding: 4,
    marginBottom: 12,
  },
  notesTabButton: {
    flex: 1,
    paddingVertical: 6,
    borderRadius: 6,
    alignItems: "center",
  },
  notesTabActive: {
    backgroundColor: "#111827",
  },
  notesTabText: {
    fontSize: 12,
    color: "#6b7280",
  },
  notesTabTextActive: {
    color: "#ffffff",
    fontWeight: "600",
  },
  noteSection: {
    marginBottom: 16,
  },
  noteDateRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  noteDateText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
  },
  noteBodyInput: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    padding: 10,
    minHeight: 160,
    textAlignVertical: "top",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  noteLink: {
    backgroundColor: "#fef3c7",
    color: "#1f2937",
    fontWeight: "600",
  },
  noteSaveButton: {
    alignSelf: "flex-start",
    backgroundColor: "#111827",
    borderRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  noteSaveButtonDisabled: {
    opacity: 0.5,
  },
  noteSaveButtonText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "600",
  },
  noteNewButton: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#111827",
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 10,
  },
  noteNewButtonText: {
    fontSize: 12,
    color: "#111827",
    fontWeight: "600",
  },
  freeNoteList: {
    marginBottom: 12,
  },
  freeNoteRow: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    backgroundColor: "#f9fafb",
  },
  freeNoteTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 4,
  },
  freeNoteMeta: {
    fontSize: 11,
    color: "#6b7280",
  },
  noteEditor: {
    borderTopWidth: 1,
    borderColor: "#e5e7eb",
    paddingTop: 12,
  },
  noteTitleInput: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  archiveBox: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 6,
    padding: 10,
  },
  archiveRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderColor: "#f3f4f6",
  },
  archiveContent: {
    flex: 1,
  },
  archiveTitle: {
    fontSize: 12,
    color: "#111827",
  },
  archiveMeta: {
    fontSize: 11,
    color: "#6b7280",
    marginTop: 2,
  },
  archiveActionButton: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginLeft: 8,
  },
  archiveActionText: {
    fontSize: 12,
    color: "#111827",
  },
  panelSectionLabel: {
    fontSize: 12,
    color: "#6b7280",
    marginBottom: 6,
    marginTop: 12,
  },
  slotBox: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 6,
    padding: 12,
    marginBottom: 12,
  },
  slotHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  slotHeaderLeftToggle: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 44,
  },
  slotChevron: {
    width: 18,
    textAlign: "center",
    fontSize: 12,
    color: "#6b7280",
    marginRight: 4,
  },
  slotHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  slotSummaryBox: {
    alignItems: "flex-end",
    marginRight: 8,
  },
  slotTitle: {
    fontSize: 16,
    fontWeight: "600",
  },
  slotCount: {
    marginLeft: 6,
    fontSize: 15,
    fontWeight: "600",
    color: "#6b7280",
  },
  slotSummary: {
    fontSize: 11,
    color: "#6b7280",
    marginRight: 8,
  },
  slotSummaryWarning: {
    color: "#dc2626",
  },
  addButton: {
    borderWidth: 1,
    borderColor: "#111827",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  addButtonText: {
    fontSize: 16,
  },
  todoTopAddButton: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 32,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#ffffff",
  },
  todoTopAddButtonText: {
    marginLeft: 4,
    fontSize: 12,
    fontWeight: "600",
    color: "#111827",
  },
  swipeRowContainer: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 6,
  },
  swipeActions: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    flexDirection: "row",
    alignItems: "stretch",
  },
  swipeActionButton: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  swipeActionText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#ffffff",
  },
  swipeMoveButton: {
    backgroundColor: "#6b7280",
  },
  swipeArchiveButton: {
    backgroundColor: "#2563eb",
  },
  swipeDeleteButton: {
    backgroundColor: "#dc2626",
  },
  swipeContent: {
    backgroundColor: "#ffffff",
  },
  taskBox: {
    borderWidth: 1,
    borderColor: "#f3f4f6",
    borderRadius: 6,
    padding: 10,
    marginBottom: 10,
  },
  completedSection: {
    borderTopWidth: 1,
    borderColor: "#f3f4f6",
    paddingTop: 6,
  },
  completedToggleRow: {
    paddingVertical: 6,
  },
  completedToggleText: {
    fontSize: 12,
    color: "#111827",
  },
  completedEmptyText: {
    fontSize: 11,
    color: "#9ca3af",
    paddingVertical: 4,
  },
  completedTaskRow: {
    flexDirection: "row",
    alignItems: "stretch",
    paddingVertical: 6,
  },
  completedTaskBody: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  completedTaskContent: {
    flex: 1,
  },
  completedTaskTitle: {
    fontSize: 12,
    color: "#9ca3af",
    textDecorationLine: "line-through",
  },
  completedTaskTime: {
    fontSize: 11,
    color: "#6b7280",
    marginTop: 2,
  },
  taskHeaderRow: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  statusBar: {
    width: 4,
    borderRadius: 2,
    marginRight: 8,
    alignSelf: "stretch",
  },
  taskHeaderBody: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
  },
  checkbox: {
    paddingHorizontal: 2,
    marginRight: 8,
    justifyContent: "center",
  },
  checkboxText: {
    fontSize: 12,
    color: "#111827",
  },
  taskHeaderPressable: {
    flex: 1,
    paddingVertical: 4,
    paddingHorizontal: 4,
    borderRadius: 4,
    justifyContent: "center",
  },
  taskHeaderActive: {
    backgroundColor: "#f9fafb",
  },
  taskHeaderContent: {},
  taskHeaderTitle: {
    fontSize: 12,
    color: "#111827",
  },
  taskHeaderTitleDone: {
    color: "#9ca3af",
    textDecorationLine: "line-through",
  },
  taskHeaderMeta: {
    fontSize: 11,
    color: "#6b7280",
    marginTop: 2,
  },
  taskHeaderMetaDone: {
    color: "#9ca3af",
  },
  statusBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    marginLeft: 8,
    alignSelf: "center",
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: "600",
  },
  taskActions: {
    flexDirection: "row",
    alignItems: "center",
  },
  startButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginLeft: 8,
    justifyContent: "center",
    backgroundColor: "#111827",
    borderRadius: 6,
  },
  startButtonDisabled: {
    backgroundColor: "#9ca3af",
  },
  startButtonText: {
    fontSize: 12,
    color: "#ffffff",
    fontWeight: "600",
  },
  inlineActionButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginLeft: 8,
    justifyContent: "center",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#111827",
    backgroundColor: "#ffffff",
  },
  inlineActionText: {
    fontSize: 12,
    color: "#111827",
    fontWeight: "600",
  },
  taskDetailPanel: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    padding: 12,
    backgroundColor: "#ffffff",
  },
  taskDetailHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  taskDetailActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    marginBottom: 10,
  },
  taskDetailTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
  },
  input: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 6,
    padding: 8,
    marginBottom: 8,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  label: {
    width: 70,
    fontSize: 12,
    color: "#4b5563",
  },
  tagDropdown: {
    flex: 1,
  },
  tagDropdownButton: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  tagDropdownText: {
    fontSize: 12,
    color: "#111827",
  },
  tagDropdownList: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 6,
    marginTop: 6,
    backgroundColor: "#ffffff",
  },
  tagDropdownItem: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderColor: "#f3f4f6",
  },
  tagDropdownItemText: {
    fontSize: 12,
    color: "#111827",
  },
  tagDropdownItemTextSelected: {
    color: "#2563eb",
    fontWeight: "600",
  },
  inputInline: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 6,
    padding: 8,
  },
  todoList: {
    gap: 10,
    paddingBottom: 96,
  },
  todoViewSwitch: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    borderRadius: 12,
    padding: 4,
    marginBottom: 12,
  },
  todoViewButton: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  todoViewButtonActive: {
    backgroundColor: "#111827",
  },
  todoViewButtonText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#4b5563",
  },
  todoViewButtonTextActive: {
    color: "#ffffff",
  },
  todoItem: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    padding: 10,
    backgroundColor: "#ffffff",
  },
  todoItemHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  todoToggle: {
    width: 22,
    height: 22,
    borderWidth: 1,
    borderColor: "#9ca3af",
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  todoToggleDone: {
    borderColor: "#111827",
    backgroundColor: "#111827",
  },
  todoToggleText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
  },
  todoText: {
    fontSize: 13,
    color: "#111827",
    paddingVertical: 4,
  },
  todoTextPressable: {
    flex: 1,
  },
  todoTextDone: {
    color: "#9ca3af",
    textDecorationLine: "line-through",
  },
  todoMetaRow: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  todoRepeatBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "#e5eefc",
  },
  todoRepeatBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#1d4ed8",
  },
  todoDeleteButton: {
    marginLeft: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  todoDeleteText: {
    fontSize: 11,
    color: "#dc2626",
  },
  todoMemoText: {
    marginTop: 6,
    fontSize: 12,
    color: "#4b5563",
    lineHeight: 17,
  },
  todoTagsText: {
    marginTop: 6,
    fontSize: 11,
    color: "#6b7280",
  },
  todoReminderText: {
    fontSize: 11,
    color: "#6b7280",
    flex: 1,
  },
  todoCalendarCard: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#ffffff",
  },
  todoCalendarCell: {
    minHeight: 48,
    gap: 4,
  },
  todoCalendarDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "transparent",
  },
  todoCalendarDotActive: {
    backgroundColor: "#111827",
  },
  todoCalendarDotSelected: {
    backgroundColor: "#ffffff",
  },
  todoCalendarSection: {
    gap: 10,
  },
  todoCalendarSectionTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111827",
  },
  todoMemoInput: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    minHeight: 96,
    marginBottom: 10,
    fontSize: 12,
    lineHeight: 18,
  },
  todoDateButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  todoDateButtonText: {
    fontSize: 12,
    color: "#111827",
  },
  todoDateButtonPlaceholder: {
    color: "#9ca3af",
  },
  todoTagSection: {
    marginBottom: 8,
  },
  todoRepeatRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 4,
  },
  todoRepeatChip: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
  },
  todoRepeatChipSelected: {
    borderColor: "#111827",
    backgroundColor: "#111827",
  },
  todoRepeatChipText: {
    fontSize: 11,
    color: "#6b7280",
  },
  todoRepeatChipTextSelected: {
    color: "#ffffff",
    fontWeight: "600",
  },
  todoRepeatStateText: {
    fontSize: 11,
    color: "#6b7280",
    marginTop: 2,
  },
  todoTagChipRow: {
    flexDirection: "row",
    marginTop: 4,
    paddingRight: 8,
  },
  todoTagChip: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 8,
  },
  todoTagChipSelected: {
    borderColor: "#111827",
    backgroundColor: "#111827",
  },
  todoTagChipText: {
    fontSize: 11,
    color: "#6b7280",
  },
  todoTagChipTextSelected: {
    color: "#ffffff",
    fontWeight: "600",
  },
  todoDateOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    backgroundColor: "rgba(15, 23, 42, 0.4)",
    padding: 24,
  },
  timePickerPanel: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 16,
  },
  timePickerColumns: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  timePickerColumn: {
    width: 96,
    height: TIME_PICKER_ITEM_HEIGHT * 5,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#f9fafb",
  },
  timePickerContent: {
    paddingVertical: TIME_PICKER_SIDE_PADDING,
  },
  timePickerItem: {
    height: TIME_PICKER_ITEM_HEIGHT,
    alignItems: "center",
    justifyContent: "center",
  },
  timePickerItemText: {
    fontSize: 20,
    color: "#9ca3af",
  },
  timePickerItemTextSelected: {
    color: "#111827",
    fontWeight: "700",
  },
  timePickerColon: {
    fontSize: 22,
    color: "#111827",
    marginHorizontal: 14,
    fontWeight: "700",
  },
  actionButton: {
    borderWidth: 1,
    borderColor: "#111827",
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginRight: 8,
    marginBottom: 8,
  },
  actionButtonDisabled: {
    borderColor: "#d1d5db",
  },
  actionButtonText: {
    fontSize: 12,
  },
  actionButtonTextDisabled: {
    color: "#9ca3af",
  },
  logControls: {
    marginBottom: 12,
  },
  logAnalysisPanel: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 10,
    padding: 10,
    backgroundColor: "#ffffff",
    marginBottom: 12,
  },
  logAnalysisHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  logAnalysisTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#111827",
  },
  logAnalysisToggle: {
    fontSize: 12,
    color: "#6b7280",
  },
  logAnalysisPeriodRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 8,
  },
  logAnalysisRangeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  logAnalysisTagRow: {
    alignItems: "center",
    paddingHorizontal: 2,
    paddingBottom: 4,
  },
  logAnalysisRangeText: {
    fontSize: 11,
    color: "#111827",
    fontWeight: "600",
    marginHorizontal: 10,
    minWidth: 170,
    textAlign: "center",
  },
  logAnalysisNavButton: {
    width: 30,
    height: 28,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  logAnalysisNavButtonDisabled: {
    borderColor: "#e5e7eb",
  },
  logAnalysisNavText: {
    fontSize: 11,
    color: "#111827",
  },
  logAnalysisNavTextDisabled: {
    color: "#9ca3af",
  },
  logAnalysisChip: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 6,
    marginBottom: 4,
  },
  logAnalysisChipActive: {
    borderColor: "#111827",
    backgroundColor: "#111827",
  },
  logAnalysisChipText: {
    fontSize: 11,
    color: "#111827",
  },
  logAnalysisChipTextActive: {
    color: "#ffffff",
  },
  logAnalysisChartContainer: {
    marginTop: 8,
    width: "100%",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 10,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8fafc",
  },
  logAnalysisSummaryRow: {
    marginTop: 6,
    alignItems: "center",
  },
  logAnalysisSummaryText: {
    fontSize: 10,
    color: "#94a3b8",
  },
  logAnalysisHint: {
    marginTop: 4,
    fontSize: 10,
    color: "#6b7280",
    textAlign: "right",
  },
  viewToggleRow: {
    flexDirection: "row",
    marginBottom: 8,
  },
  viewToggleButton: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginRight: 8,
  },
  viewToggleButtonActive: {
    borderColor: "#111827",
    backgroundColor: "#111827",
  },
  viewToggleText: {
    fontSize: 12,
    color: "#111827",
  },
  viewToggleTextActive: {
    color: "#ffffff",
  },
  logSearchInput: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 6,
    padding: 8,
    marginBottom: 8,
  },
  filterRow: {
    alignItems: "center",
    paddingBottom: 4,
  },
  filterChip: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 6,
  },
  filterChipActive: {
    borderColor: "#111827",
    backgroundColor: "#111827",
  },
  filterChipText: {
    fontSize: 12,
    color: "#111827",
  },
  filterChipTextActive: {
    color: "#ffffff",
  },
  table: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 6,
    overflow: "hidden",
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderColor: "#f3f4f6",
  },
  tableHeaderRow: {
    backgroundColor: "#f9fafb",
  },
  tableCell: {
    fontSize: 12,
    paddingHorizontal: 6,
    color: "#111827",
  },
  tableCellDate: {
    width: 90,
  },
  tableCellTitle: {
    width: 140,
  },
  tableCellTag: {
    width: 140,
  },
  tableCellNumber: {
    width: 70,
    textAlign: "right",
  },
  boardRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  boardColumn: {
    width: 220,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 6,
    padding: 8,
    marginRight: 12,
  },
  boardColumnTitle: {
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 8,
  },
  boardCard: {
    borderWidth: 1,
    borderColor: "#f3f4f6",
    borderRadius: 6,
    padding: 8,
    marginBottom: 8,
  },
  boardCardTitle: {
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 4,
  },
  boardCardMeta: {
    fontSize: 11,
    color: "#4b5563",
    marginBottom: 2,
  },
  logLandscapeTable: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    overflow: "hidden",
  },
  logLandscapeRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderColor: "#f3f4f6",
  },
  logLandscapeHeaderRow: {
    alignItems: "center",
    backgroundColor: "#f9fafb",
  },
  logLandscapeHeaderCell: {
    fontSize: 11,
    color: "#6b7280",
    fontWeight: "600",
  },
  logLandscapeHeaderMetric: {
    textAlign: "right",
  },
  logLandscapeMetaCell: {
    flex: 2.2,
    paddingRight: 8,
  },
  logLandscapeMetricCell: {
    flex: 1,
    paddingHorizontal: 6,
  },
  logLandscapeDiffCell: {
    flex: 1.2,
    paddingLeft: 6,
  },
  logLandscapeTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 2,
    flexShrink: 1,
  },
  logLandscapeTitleRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  logLandscapeTags: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 6,
    flexShrink: 0,
  },
  logLandscapeTagChip: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#f9fafb",
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 1,
    marginLeft: 4,
  },
  logLandscapeTagText: {
    fontSize: 10,
    color: "#6b7280",
  },
  logLandscapeTagChipMuted: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#f8fafc",
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 1,
    marginLeft: 4,
  },
  logLandscapeTagTextMuted: {
    fontSize: 10,
    color: "#9ca3af",
  },
  logLandscapeMeta: {
    fontSize: 10,
    color: "#6b7280",
  },
  logLandscapeValue: {
    fontSize: 12,
    fontWeight: "600",
    color: "#111827",
    textAlign: "right",
  },
  sheetOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  sheetBackdrop: {
    flex: 1,
  },
  sheetContainer: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 24,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#e5e7eb",
    marginBottom: 8,
  },
  sheetTitle: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
  },
  sheetItem: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  sheetItemText: {
    fontSize: 14,
    color: "#111827",
  },
  sheetItemInline: {
    flexDirection: "row",
    alignItems: "center",
  },
  sheetItemTextWithIcon: {
    marginLeft: 8,
  },
  sheetHelpButton: {
    alignSelf: "flex-start",
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginBottom: 6,
  },
  sheetHelpText: {
    fontSize: 12,
    color: "#2563eb",
    textDecorationLine: "underline",
  },
  sheetCloseButton: {
    marginTop: 4,
    alignSelf: "flex-start",
    paddingVertical: 8,
  },
  sheetCloseText: {
    fontSize: 12,
    color: "#6b7280",
  },
  dateOverlay: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(15, 23, 42, 0.4)",
    padding: 24,
  },
  dateBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  datePanel: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 16,
  },
  dateTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 12,
  },
  dateShiftRow: {
    flexDirection: "row",
    marginBottom: 12,
  },
  dateShiftButton: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginRight: 8,
  },
  dateShiftText: {
    fontSize: 12,
    color: "#111827",
  },
  dateInput: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    marginBottom: 10,
  },
  calendarHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  calendarMonthButton: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  calendarMonthButtonText: {
    fontSize: 12,
    color: "#111827",
  },
  calendarMonthLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
  },
  calendarWeekdayRow: {
    flexDirection: "row",
    marginBottom: 6,
  },
  calendarWeekdayText: {
    width: `${100 / 7}%`,
    textAlign: "center",
    fontSize: 11,
    color: "#6b7280",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 8,
  },
  calendarCell: {
    width: `${100 / 7}%`,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 7,
    borderRadius: 8,
  },
  calendarCellSelected: {
    backgroundColor: "#111827",
  },
  calendarCellText: {
    fontSize: 12,
    color: "#111827",
  },
  calendarCellTextMuted: {
    color: "#9ca3af",
  },
  calendarCellTextSelected: {
    color: "#ffffff",
    fontWeight: "600",
  },
  dateActionRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 8,
  },
  dateActionButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  dateActionText: {
    fontSize: 13,
    color: "#111827",
  },
  dateActionPrimary: {
    backgroundColor: "#111827",
    borderRadius: 8,
    marginLeft: 8,
  },
  dateActionPrimaryText: {
    color: "#ffffff",
    fontWeight: "600",
  },
  downloadNoticeOverlay: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(15, 23, 42, 0.5)",
    padding: 24,
  },
  downloadNoticeBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  downloadNoticePanel: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 20,
  },
  downloadNoticeTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 10,
  },
  downloadNoticeBody: {
    fontSize: 14,
    lineHeight: 20,
    color: "#334155",
    marginBottom: 16,
  },
  downloadNoticeLink: {
    color: "#2563eb",
    textDecorationLine: "underline",
  },
  downloadNoticeButton: {
    alignSelf: "flex-end",
    backgroundColor: "#111827",
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  downloadNoticeButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "600",
  },
  languagePickerActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  languagePickerButton: {
    marginLeft: 8,
  },
  moveSlotRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 4,
  },
  moveSlotButton: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  moveSlotButtonActive: {
    borderColor: "#2563eb",
    backgroundColor: "#eff6ff",
  },
  moveSlotText: {
    fontSize: 12,
    color: "#111827",
  },
  moveSlotTextActive: {
    color: "#1d4ed8",
    fontWeight: "600",
  },
  footer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: FOOTER_HEIGHT,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#f9fafb",
    paddingHorizontal: 8,
    paddingBottom: 6,
  },
  inProgressFooterButton: {
    flex: 1,
    maxWidth: 240,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#111827",
    backgroundColor: "#ffffff",
  },
  inProgressFooterText: {
    fontSize: 12,
    color: "#111827",
    fontWeight: "600",
  },
  tabBar: {
    flexDirection: "row",
    alignItems: "stretch",
    borderTopWidth: Platform.OS === "ios" ? StyleSheet.hairlineWidth : 1,
    borderColor:
      Platform.OS === "ios" ? "rgba(15, 23, 42, 0.12)" : "#e5e7eb",
    backgroundColor: "#ffffff",
    ...(Platform.OS === "ios"
      ? {
          shadowColor: "#0f172a",
          shadowOpacity: 0.08,
          shadowRadius: 12,
          shadowOffset: { width: 0, height: -6 },
        }
      : {
          elevation: 6,
        }),
  },
  tabButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 10,
    paddingBottom: 10,
    paddingHorizontal: 16,
  },
  tabButtonActive: {
    backgroundColor: "#f9fafb",
  },
  tabButtonPressed: {
    backgroundColor: "#f3f4f6",
  },
  tabLabel: {
    fontSize: 13,
    color: "#6b7280",
    fontWeight: "500",
    letterSpacing: 0.2,
  },
  tabLabelActive: {
    color: "#111827",
    fontWeight: "700",
  },
  tabIndicator: {
    position: "absolute",
    top: 0,
    left: 16,
    right: 16,
    height: 2,
    borderRadius: 999,
    backgroundColor: "transparent",
  },
  tabIndicatorActive: {
    backgroundColor: "#111827",
  },
});

export default styles;
