const fs = require("fs");
const path = require("path");
const { createRunOncePlugin, withDangerousMod } = require("@expo/config-plugins");

const PLUGIN_MARKER = "# @generated by withReactNativeFirebaseIos";
const POST_INSTALL_MARKER =
  "    # @generated by withReactNativeFirebaseIos: scoped RNFirebase header compatibility";

const RNFIREBASE_POST_INSTALL = `${POST_INSTALL_MARKER}
    installer.pods_project.targets.each do |target|
      next unless ['RNFBApp', 'RNFBCrashlytics'].include?(target.name)

      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
`;

const patchCrashlyticsModule = (contents) => {
  const directImport = "#import <React/RCTBridgeModule.h>";
  if (contents.includes(directImport)) {
    return contents;
  }
  return contents.replace(
    "#import <React/RCTConvert.h>",
    `${directImport}\n#import <React/RCTConvert.h>`,
  );
};

const patchPodfile = (contents) => {
  let next = contents.replace(/^\s*use_modular_headers!\s*\n/gm, "");
  if (!next.includes(PLUGIN_MARKER)) {
    next = next.replace(
      /(platform :ios[^\n]*\n)/,
      `$1${PLUGIN_MARKER}\n$RNFirebaseAsStaticFramework = true\n`,
    );
  }
  if (!next.includes(POST_INSTALL_MARKER)) {
    next = next.replace(
      /(\s+react_native_post_install\([\s\S]*?\n\s+\)\n)/,
      `$1${RNFIREBASE_POST_INSTALL}`,
    );
  }
  return next;
};

const withReactNativeFirebaseIos = (config) =>
  withDangerousMod(config, [
    "ios",
    async (config) => {
      const podfilePath = path.join(
        config.modRequest.platformProjectRoot,
        "Podfile",
      );
      const contents = await fs.promises.readFile(podfilePath, "utf8");
      const next = patchPodfile(contents);
      if (next !== contents) {
        await fs.promises.writeFile(podfilePath, next);
      }

      // RNFirebase 25.1.0 does not import the bridge macro definitions directly
      // in this implementation file. Xcode 26 explicit modules therefore hide
      // RCT_EXPORT_* even though the public header imports RCTBridgeModule.h.
      const crashlyticsModulePath = path.join(
        config.modRequest.projectRoot,
        "node_modules",
        "@react-native-firebase",
        "crashlytics",
        "ios",
        "RNFBCrashlytics",
        "RNFBCrashlyticsModule.m",
      );
      const crashlyticsContents = await fs.promises.readFile(
        crashlyticsModulePath,
        "utf8",
      );
      const patchedCrashlyticsContents = patchCrashlyticsModule(
        crashlyticsContents,
      );
      if (patchedCrashlyticsContents !== crashlyticsContents) {
        await fs.promises.writeFile(
          crashlyticsModulePath,
          patchedCrashlyticsContents,
        );
      }
      return config;
    },
  ]);

module.exports = createRunOncePlugin(
  withReactNativeFirebaseIos,
  "with-react-native-firebase-ios",
  "1.0.0",
);
